### ISSUE TITLE
EE breaking visual/text tabs on WYSIWYG editors in Page Builder modules.

### ISSUE THREAD

**Issue by jshrssll** [eventespresso/eea-beaver-builder#13] opened 2018-05-01 01:29 UTC
Hello,

We have Event Espresso installed on our site, however we are also using Beaver Builder’s Page Builder module to author non-EE pages.

What we have noticed is that for pages that have WYSIWYG modules, the Visual/Text tabs have disappeared. When EE is disabled, these tabs reappear.

I’m just wonder if you have any idea of why EE is getting in the way of Page Builder and how we can rectify it.

Cheers!

**Comment by mnelson4** [comment] 2018-05-01 02:48
@splurtcake do you have the Event Espresso Beaver Builder add-on active? It sounds like this potentially a conflict between Event Espresso and Beaver Builders, and it doesn't actually have anything to do with this repository's add-on.

**Comment by jshrssll** [comment] 2018-05-01 03:09
@mnelson4 Hey Mike, I figured as much... It doesn't relate to this plugin and we do not have it installed. We only have core EE and BB Page Builder.

I did post on the forums initially and was instructed by Josh to post in here, although I did clarify that they're probably not related — https://eventespresso.com/topic/ee-breaking-beaver-builder-page-builder-wysiwyg-visual-text-tabs/

Cheers

**Comment by mnelson4** [comment] 2018-05-01 17:44
ah ok- ya good to know you checked with support first.

I see @Pebblo discovered the issue and made a suggestion here: https://eventespresso.com/topic/ee-breaking-beaver-builder-page-builder-wysiwyg-visual-text-tabs/#post-268371

I'm seeing if we can add that as a compatibility shim to this EE-BB add-on

**Comment by mnelson4** [comment] 2018-05-01 17:50
@splurtcake I put Tony's suggested fix into branch hidden-bb-WYSIWYG of this add-on. So you could try downloading this add-on on that branch and confirmt the issue is resolved

**Comment by mnelson4** [comment] 2018-05-01 19:37
that work got reviewed and was merged into master. From my testing it resolved the issue @splurtcake reported

**Closed as completed by mnelson4** 2018-05-01 19:37 UTC

**Comment by jshrssll** [comment] 2018-05-01 23:38
Thanks guys!
